# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  displayName: Build an image
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    containerRegistry: 'dsptconection'
    repository: 'dsptalks/dsp'
    tags: |
          1
- task: AzureAppServiceManage@0
  displayName: Stop Application
  inputs:
    azureSubscription: 'Free Trial(6d49fee0-da31-4691-a265-f0943b5973f9)'
    Action: 'Stop Azure App Service'
    WebAppName: 'dsptnew'

- task: AzureWebAppContainer@1
  displayName: Deploy Container on dsptnew app
  inputs:
    azureSubscription: 'Free Trial(6d49fee0-da31-4691-a265-f0943b5973f9)'
    appName: 'dsptnew'
    containers: 'dsptalks/dsp:1'

- task: AzureAppServiceManage@0
  displayName: Start Application
  inputs:
    azureSubscription: 'Free Trial(6d49fee0-da31-4691-a265-f0943b5973f9)'
    Action: 'Start Azure App Service'
    WebAppName: 'dsptnew'

